#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: journal_dev
#      auto-index-creation: true
#
#server:
#  port: 8081
#
#logging:
#  level:
#    org.springframework: DEBUG
